export enum ErrorCode {
  // Users
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_DISABLED = 'USER_DISABLED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Database
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_CONSTRAINT_VIOLATION = 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
